schema_version = "1.0.0"

id = "dynamiclinkmanager"
name = "Dynamic Link Manager"
tagline = "Character migrator and linked library tools"
version = "0.1.2"
type = "add-on"

# Optional: Semantic Versioning
maintainer = "RaincloudTheDragon <raincloudthedragon@gmail.com>"
license = ["GPL-3.0-or-later"]
blender_version_min = "4.5.0"

website = "https://github.com/RaincloudTheDragon/Dynamic-Library-Manager"

tags = ["3D View"]