schema_version = "1.0.0"
id = "dynamiclinkmanager"
version = "0.5.1"
name = "Dynamic Link Manager"
tagline = "Dynamic Link Manager"
maintainer = "RaincloudTheDragon"
type = "add-on"
tags = ["3D View"]
blender_version_min = "4.5.0"
license = [
"SPDX:GPL-2.0-or-later",
]